#! /bin/sh
# /etc/init.d/gaggia

### BEGIN INIT INFO
# Provides:          gaggia
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to start Gaggia controller at boot
# Description:       Script to start Gaggia controller at boot
### END INIT INFO

# If you want a command to always run, put it here

# Set up the timezone
if [ -z "$TZ" -a -e /etc/timezone ]; then
    TZ=`cat /etc/timezone`
    export TZ
fi

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Gaggia"
    # run application
    /usr/local/bin/gaggia start &
    ;;
  stop)
    echo "Stopping Gaggia"
    # kill application
    killall gaggia
    # turn off the boiler
    /usr/local/bin/gaggia stop
    ;;
  *)
    echo "Usage: /etc/init.d/gaggia {start|stop}"
    exit 1
    ;;
esac

exit 0
